### ISSUE TITLE
create zfs snapshots in the ui

### ISSUE THREAD

**Issue by j-keck** [j-keck/zfs-snap-diff#1]
`zfs-snap-diff` should provide the functionality to create zfs snapshots in the ui.

---

_This issue is to discuss features of zfs-snap-diff._
_Please comment or upvote (:+1:) if you need the feature / downvote (:-1:) if you doesn't._

**Comment by priyadarshan** [comment]
This would be interesting especially if the naming would be configurable via `ini` file. In that way it would not interfere with other tools.

**Comment by j-keck** [comment]
This is implemented in the next version.
