### ISSUE TITLE
ideal output format for integration with snapshot-timemachine

### ISSUE THREAD

**Issue by kryptt** [j-keck/zfs-snap-diff#12]
Hi, I am currently working on a pull request (mrBliss/snapshot-timemachine#4) to integrate this tool directly within emacs. 

I'm currently using the verbose debug output (-v) to capture the dataset mount path.

An optimal listing would be in to form: 

idx | snapshot name | snapshot file | file date

so if currently running `zsd -d 15 .spacemacs list` outputs 

|  # | Snapshot                           | Snapshot age                                 |
|--- | --- | --- | 
|  0 | autosnap_2020-06-11_23:59:00_daily | 5 days                           |            
|  1 | autosnap_2020-06-04_23:59:05_daily | 12 days                          |            

I would benefit from running `zfs -d 15 --timemachine .spacemacs list` to output

|  # | Snapshot                           | Snapshot file      | File Date                                 |
|--- | --- | --- | --- |
|  0 | autosnap_2020-06-11_23:59:00_daily | /home/rhansen/.zfs/snapshot/autosnap_2020-06-11_23:59:00_daily/.spacemacs | Jun  5 23:14                             |
|  1 | autosnap_2020-06-04_23:59:05_daily | /home/rhansen/.zfs/snapshot/autosnap_2020-06-04_23:59:05_daily/.spacemacs | Jun 12 15:15          |

An additional option to omit the headers would be a nice extra. 

What do you think?

**Comment by j-keck** [comment]
Hey,

if it's ok for you, i would use the `-snapshot-timemachine` flag for this.

Did you need a header, or always remove it?

would this output format ok for you?
```
..priv/zfs-snap-diff⟩ ./zsd -snapshot-timemachine  cmd/zsd/main.go  list
0	zfs-auto-snap_hourly-2020-06-17-13h00U	/home/.zfs/snapshot/zfs-auto-snap_hourly-2020-06-17-13h00U/j/prj/priv/zfs-snap-diff/cmd/zsd/main.go	Jun 17 15:00
1	zfs-auto-snap_frequent-2020-06-17-12h45U	/home/.zfs/snapshot/zfs-auto-snap_frequent-2020-06-17-12h45U/j/prj/priv/zfs-snap-diff/cmd/zsd/main.go	Jun 17 14:45
```
 With the `-snapshot-timemachine` flag, the output would be:
  * without header
  * fields separated with a single tab
  * filepath in the snapshot included
  * absolute date (MMM D HH:MI)

i have implemented a prototype in 39822c490e40d96f430d7442395697ead7083ec7

**Comment by kryptt** [comment]
yup, that works perfectly fine!

**Comment by j-keck** [comment]
The build currently fails, so the artifacts are not build: https://github.com/j-keck/zfs-snap-diff/runs/780753110

I'm on it.

**Comment by j-keck** [comment]
build fixed and the new version with the changes are released: 
https://github.com/j-keck/zfs-snap-diff/releases/tag/v1.1.1

**Comment by priyadarshan** [comment]
This is fantastic, thank you!
