### ISSUE TITLE
Nix derivation fails to build

### ISSUE THREAD

**Issue by ethanhs** [j-keck/zfs-snap-diff#14]
It seems that the nix derivation tries to build using a broken version of the purescript nix library it uses (one of the downloads 403s). Would it be possible to get an updated nix derivation?

The tool looks really cool, I'd love to try it out.

**Comment by j-keck** [comment]
Hey @ethanhs, I just saw the issue - sorry!
There were too many notifications in the past - didn't have time today, but I will check it in the coming days.

**Comment by ethanhs** [comment]
No worries at all, I know a wall of notifications can be a lot to deal with. I appreciate you looking into it.

**Comment by j-keck** [comment]
Fixed in 03d1700 (build was failing because of the cross-compile pipeline).

Sorry for this long delay and thanks for the report!

**Comment by emmatyping** [comment]
Thanks for the fix and the neat project :)
