### ISSUE TITLE
automatic create / destroy zfs snapshots

### ISSUE THREAD

**Issue by j-keck** [j-keck/zfs-snap-diff#2]
**`zfs-snap-diff` should automatic create / destroy zfs snapshots**

or this is the job for:
- [zfsnap/zfsnap](https://github.com/zfsnap/zfsnap)
- [bdrewery/zfstools](https://github.com/bdrewery/zfstools)
- [zfsonlinux/zfs-auto-snapshot](http://github.com/zfsonlinux/zfs-auto-snapshot)

---

_This issue is to discuss features of zfs-snap-diff._
_Please comment or upvote (:+1:) if you need the feature / downvote (:-1:) if you doesn't._

**Comment by priyadarshan** [comment]
Sometimes snapshots have custom naming templates, depending on which tool one uses, and accidentally destroying some snapshot may lead to data loss. Personally I would prefer to delegate this feature to other tools.

**Comment by j-keck** [comment]
this is a task for a zfs snapshot tool - so i close this.
