### ISSUE TITLE
the backup location should be under `~/.zsd/...`

### ISSUE THREAD

**Issue by j-keck** [j-keck/zfs-snap-diff#3]
currently the backup location for files, which are restored from a snapshot is under `/path/where/the/file/was/.zsd/<FILE_NAME>_<TIMESTAMP>`. 
`zfs-snap-diff` should put the backups under `~/.zsd/...`.

---

_This issue is to discuss features of zfs-snap-diff._
_Please comment or upvote (:+1:) if you need the feature / downvote (:-1:) if you doesn't._

**Comment by priyadarshan** [comment]
It would be nice if this was selectable via `ini` file read by `zfs-snap-diff` at launch time.

**Comment by j-keck** [comment]
this is implemented in the next version v1.0.0
