### ISSUE TITLE
HTTPS / SSL Support

### ISSUE THREAD

**Issue by jsirianni** [j-keck/zfs-snap-diff#7]
I think I would love to try this, but it appears to only support HTTP. Please correct me if I am wrong. 

This is a concern for me because it would be deployed on production servers.

**Comment by hillsy** [comment]
You can deploy it behind a reverse proxy such as Apache, that supports SSL.
This is what we did though we ended up not using the tool for other, unrelated, reasons.

**Comment by jsirianni** [comment]
Totally understandable, not sure why I did not think of that. Thanks!
