### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by j4jes** [j-keck/zfs-snap-diff#9]
Just tried this, and it looks broken on Centos7. In the web UI I click on a snapshot under diff and it just gives a spinning wheel endlessly, even when I click elsewhere.

Also there is an option to specify a port other than 12345 but if I try to specify a specific interface like -p 172.100.100.101:12345 ,it doesn't work. I don't want to launch this on all interfaces (-a), this is very insecure.

**Comment by j-keck** [comment]
Sorry for the delayed response.

### Doesn't work

a.) how many snapshots did you have? can you post the output of

    zfs list -t snapshot -r <YOUR_DATASET> | wc -l

a.) can you please start `zfs-snap-diff` with the `'-v'` flag, and post the output here?


### Access restrictions
with the `-p` flag, you can only provide the port. i just released a new version [0.0.10](https://github.com/j-keck/zfs-snap-diff/releases/tag/0.0.10) where you
can specify the listen address with the `-l` flag:

    zfs-snap-diff -l 172.100.100.101 -p 12345 .....

and with this version, you can use it behind a reverse-proxy like nginx (see the example snippet)
and than you can use nginx auth features.

i have included the possibility to use a https connection - the next step is to add a token to all endpoints.
this is security releated, so it's not a quick hack and needs testing - maybe next week.

you can alwas let `zfs-snap-diff`listen on localhost and use a ssh tunnel to your server:

     ssh -L 12345:127.0.0.1:12345 <REMOTE_HOST_WHERE_ZFS_SNAP_DIFF_RUNS>

and then open your browser on your machine: http://localhost:12345
